services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: gateway/gateway.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter1:
        condition: service_started
      
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      #- ./movies_metadata.csv:/app/movies_metadata.csv
      - ./movies_2000_lines.csv:/app/movies_metadata.csv

  filter1:
    build:
      context: .
      dockerfile: filter/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
