services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: gateway/gateway.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_one_prod_1:
        condition: service_started
      filter_spain_argentina_1:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./movies_metadata.csv:/app/movies_metadata.csv

  filter_spain_argentina_1:
    build:
      context: .
      dockerfile: filter/filter_spain_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_years_2000_1:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
  
  filter_years_2000_1:
    build:
      context: .
      dockerfile: filter/filter_years_2000/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1

  filter_one_prod_1:
    build:
      context: .
      dockerfile: filter/filter_one_prod/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      group_by_country_1:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1

  group_by_country_1:
    build:
      context: .
      dockerfile: group_by/group_by_country/group_by.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_budget_1:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1

  top_budget_1:
    build:
      context: .
      dockerfile: top/top_budget/top.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1