services: 
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: gateway/gateway.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_argentina_1:
        condition: service_started
      filter_argentina_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./movies_metadata.csv:/app/movies_metadata.csv
      - ./ratings.csv:/app/ratings.csv

  filter_argentina_1:
    build:
      context: .
      dockerfile: filter/filter_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_years_2000_argentina_1:
        condition: service_started
      filter_years_2000_argentina_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4

  filter_argentina_2:
    build:
      context: .
      dockerfile: filter/filter_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_years_2000_argentina_1:
        condition: service_started
      filter_years_2000_argentina_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9

  filter_years_2000_argentina_1:
    build:
      context: .
      dockerfile: filter/filter_years_2000_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      join_ratings_1:
        condition: service_started
      join_ratings_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4
    
  filter_years_2000_argentina_2:
    build:
      context: .
      dockerfile: filter/filter_years_2000_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      join_ratings_1:
        condition: service_started
      join_ratings_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9

  join_ratings_1:
    build:
      context: .
      dockerfile: join/join_ratings/join.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      group_by_movie_1:
        condition: service_started
      group_by_movie_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4

  join_ratings_2:
    build:
      context: .
      dockerfile: join/join_ratings/join.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      group_by_movie_1:
        condition: service_started
      group_by_movie_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9

  group_by_movie_1:
    build:
      context: .
      dockerfile: group_by/group_by_movie/group_by.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_rating_1:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4

  group_by_movie_2:
    build:
      context: .
      dockerfile: group_by/group_by_movie/group_by.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_rating_1:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9

  top_rating_1:
    build:
      context: .
      dockerfile: top/top_rating/top.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4,5,6,7,8,9