services: 
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: gateway/gateway.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_argentina_1:
        condition: service_started
      filter_argentina_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./movies_metadata.csv:/app/movies_metadata.csv
      - ./ratings_39999_lines.csv:/app/ratings.csv
      - ./credits.csv:/app/credits.csv

  filter_argentina_1:
    build:
      context: .
      dockerfile: filter/filter_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_years_2000_argentina_1:
        condition: service_started
      filter_years_2000_argentina_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4
      - CONSUMER_EXCHANGE=gateway_metadata
      - PUBLISHER_EXCHANGE=filter_argentina

  filter_argentina_2:
    build:
      context: .
      dockerfile: filter/filter_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_years_2000_argentina_1:
        condition: service_started
      filter_years_2000_argentina_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9
      - CONSUMER_EXCHANGE=gateway_metadata
      - PUBLISHER_EXCHANGE=filter_argentina

  filter_years_2000_argentina_1:
    build:
      context: .
      dockerfile: filter/filter_years_2000_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      join_ratings_1:
        condition: service_started
      join_ratings_2:
        condition: service_started
      join_credits_1:
        condition: service_started
      join_credits_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4
      - CONSUMER_EXCHANGE=filter_argentina
      - PUBLISHER_EXCHANGE=filter_years_2000_argentina
    
  filter_years_2000_argentina_2:
    build:
      context: .
      dockerfile: filter/filter_years_2000_argentina/filter.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      join_ratings_1:
        condition: service_started
      join_ratings_2:
        condition: service_started
      join_credits_1:
        condition: service_started
      join_credits_2:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9
      - CONSUMER_EXCHANGE=filter_argentina
      - PUBLISHER_EXCHANGE=filter_years_2000_argentina

  join_ratings_1:
    build:
      context: .
      dockerfile: join/join_ratings/join.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_rating:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4
      - CONSUMER_EXCHANGE_METADATA=filter_years_2000_argentina
      - CONSUMER_EXCHANGE_JOINED=gateway_ratings
      - PUBLISHER_EXCHANGE=join_ratings

  join_ratings_2:
    build:
      context: .
      dockerfile: join/join_ratings/join.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_rating:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9
      - CONSUMER_EXCHANGE_METADATA=filter_years_2000_argentina
      - CONSUMER_EXCHANGE_JOINED=gateway_ratings
      - PUBLISHER_EXCHANGE=join_ratings

  join_credits_1:
    build:
      context: .
      dockerfile: join/join_credits/join.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_actors:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4
      - CONSUMER_EXCHANGE_METADATA=filter_years_2000_argentina
      - CONSUMER_EXCHANGE_JOINED=gateway_credits
      - PUBLISHER_EXCHANGE=join_credits

  join_credits_2:
    build:
      context: .
      dockerfile: join/join_credits/join.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      top_actors:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=5,6,7,8,9
      - CONSUMER_EXCHANGE_METADATA=filter_years_2000_argentina
      - CONSUMER_EXCHANGE_JOINED=gateway_credits
      - PUBLISHER_EXCHANGE=join_credits

  top_rating:
    build:
      context: .
      dockerfile: generic/top_rating/generic.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4,5,6,7,8,9
      - CONSUMER_EXCHANGE=join_ratings
      - PUBLISHER_EXCHANGE=results

  top_actors:
    build:
      context: .
      dockerfile: generic/top_actors/generic.dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_ID=1
      - BINDS=0,1,2,3,4,5,6,7,8,9
      - CONSUMER_EXCHANGE=join_credits
      - PUBLISHER_EXCHANGE=results